### PR TITLE
RAG with doc nums

### PR DESCRIPTION
**Pull request by densumesh**

### CODE REVIEW

**Comment by densumesh** [comment]
https://github.com/arguflow/arguflow/assets/25559111/abe57d15-8625-481e-87b5-9b964d712f2f

**Comment by densumesh** [comment]
image

**Comment by skeptrunedev** [comment]
image

**Review by skeptrunedev — APPROVED** [review]
This looks good. It's a complex system, so I'm not 100% this works, but I think any remaining bugs should be very minor.

**Pull request merged**
