### PR TITLE
bugfix: hide show more button on ScoreCard and CardMetadataDisplay until after hydration

### LINKED ISSUE #455: bugfix: hide show more button on ScoreCard and CardMetadataDisplay until after hydration
### Description

For the `search` UI, there is currently a bug where if you expand a card before the client hydrates it, the card will become collapsed again after hydration goes through. 

client-hydration-bug

The fix for this is not allowing the user to expand before hydration occurs by not showing the button if `window` is undefined. 

### Target(s)

`search`

### Requirement to close

- [ ] the "show more" button does not show until after the card component has been hydrated for both `ScoreCard.tsx` and `CardMetadataDisplay.tsx`

### PR commit requirements for a bounty claim

This PR should have only one commit titled as below.

- [ ] bugfix: hide show more button on ScoreCard and CardMetadataDisplay until after hydration

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #455
/claim #455

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@skeptrunedev 

What's happening here is that the whole component is being rendered multiple times (due to fetches in the parent components that cause to mutate the signal(s) which result in rerender)

What I tried to do here is observe the changes, and after a certain limit if there are no changes, the button is displayed given that the changes atleast occured once.

**Comment by skeptrunedev** [comment]
> @skeptrunedev 
> 
> What's happening here is that the whole component is being rendered multiple times (due to fetches in the parent components that cause to mutate the signal(s) which result in rerender)
> 
> What I tried to do here is observe the changes, and after a certain limit if there are no changes, the button is displayed given that the changes atleast occured once.

Yeah, I am aware of how it worked. The Astro server does not forward auth cookies to the API server (security risk to do that) so we make the same search request a second time client side after the SSR renders.

You could probably just wait for the client side (second) search request (single card, collection cards, etc.) to load and then set a signal val to true.

If that signal is true, Render the show button.

Looked at your code a bit, and it will likely require a redo. Will tip something regardless of merge. Partially my fault for not explaining more in the issue.

**Comment by rishi-raj-jain** [comment]
> You could probably just wait for the client side (second) search request (single card, collection cards, etc.) to load and then set a signal val to true.

But this won't be limited to the ScoreCard.tsx, correct?

**Comment by rishi-raj-jain** [comment]
All the places where it's used is where I'd need to make the change, correct? Just confirming.

**Comment by skeptrunedev** [comment]
> All the places where it's used is where I'd need to make the change, correct? Just confirming as the issue said you required it only in those components.

Yep. This is my fault for spec'ing the issue terribly. Your work here is good. Will check it against the issue and if it meets the requirements I wrote we will payout the bounty.

My fault for not thinking it through.

**Comment by skeptrunedev** [comment]
> All the places where it's used is where I'd need to make the change, correct? Just confirming as the issue said you required it only in those components.

Correct. And would need to pass through a prop from ScoreCardArray to DcoreCard if I remember correctly.

**Comment by rishi-raj-jain** [comment]
> Correct. And would need to pass through a prop from ScoreCardArray to ScoreCard if I remember correctly.

Thanks for pointing this out, I'm working on it.

**Comment by rishi-raj-jain** [comment]
> Yep. This is my fault for spec'ing the issue terribly.

No worries! I'm on it.

**Comment by rishi-raj-jain** [comment]
>  Your work here is good. Will check it against the issue and if it meets the requirements I wrote we will payout the bounty.

Appreciate the kind words. For sure, I'll do the signal drilling correctly!

> My fault for not thinking it through.

No worries man, definitely not something we can not handle 🤟🏻 after all we're engineers :)

**Comment by skeptrunedev** [comment]
This is currently very far off from being a viable merge candidate, so I am going to close for now.

**Comment by rishi-raj-jain** [comment]
@skeptrunedev I'd love to work on this, can you re-open this?

**Comment by rishi-raj-jain** [comment]
Can put this into the draft mode if you prefer that, but would like to continue the work I am putting into it...

**Comment by skeptrunedev** [comment]
> Can put this into the draft mode if you prefer that, but would like to continue the work I am putting into it...

Just merged a fix that closes the issue --> https://github.com/arguflow/arguflow/pull/471

Will add a tip on the other PR as an apology for the poor spec in the issue on this one.

**Comment by rishi-raj-jain** [comment]
@skeptrunedev

> Just merged a fix that closes the issue --> https://github.com/arguflow/arguflow/pull/471

Checking it out

> Will add a tip on the other PR as an apology for the poor spec in the issue on this one.

Would love to get the amount as promised for this one ✨

**Comment by skeptrunedev** [comment]
So I tested this exact PR and it did not quite do what was specced in the issue as the "Show More" button never seemed to appear. Some of this is my fault for providing poor directions, but I am only going to tip $10 as a result of that mistake. Had this PR been a full solution (even if not ideal), I would tip the full amount.

**Pull request closed without merging**
