### PR TITLE
feature: use env! macro to throw error's at compile time.

### LINKED ISSUE #246: feature: use env! macro to throw error's at compile time.
This is for the `server` folder. Everywhere than an `env` var is loaded should throw an error at compile if it is not present once this issue is resolved.

However, the exception is env vars that are optional. Do not make them required please.

### PR DESCRIPTION
**Pull request by tobihans**
This PR closes #246.
/claim #246

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Closing this as @anikdhabal has a more complete version live. 

Make sure to star the repo!!!

**Comment by tobihans** [comment]
I see. I saw his own has a lot of mistakes essentially related to Rust syntax. That's the only reason I continued, otherwise I would have closed it myself. Thanks.

**Comment by tobihans** [comment]
Thanks, I'm in the process of solving the merge conflict now.

**Comment by skeptrunedev** [comment]
> I see. I saw his own has a lot of mistakes essentially related to Rust syntax. That's the only reason I continued, otherwise I would have closed it myself. Thanks.

You actually make quite a good point 😅.

I closed this before I really reviewed the other claim. It's a long ways off being correct honestly.

Reopened. We will merge and reward the first PR that accurately resolves the issue. 

In  the future we will make a policy for this so it doesn't happen again.

**Comment by tobihans** [comment]
@skeptrunedev It's fine now. I extended it to load the env from the build script as you suggested in the other PR. Thanks

**Comment by tobihans** [comment]
> I closed this before I really reviewed the other claim. It's a long ways off being correct honestly.
> In the future we will make a policy for this so it doesn't happen again.

I guess that was AI-generated.

**Comment by skeptrunedev** [comment]
> > I closed this before I really reviewed the other claim. It's a long ways off being correct honestly.
> > In the future we will make a policy for this so it doesn't happen again.
> 
> I guess that was AI-generated.

No lol. Assuming this compiles and it works it was done first and will be the PER merged. Just 2am for me. Going to sleep and will review and merge when I wake up.

**Comment by anikdhabal** [comment]
> > I closed this before I really reviewed the other claim. It's a long ways off being correct honestly.
> > In the future we will make a policy for this so it doesn't happen again.
> 
> I guess that was AI-generated.

Pls show me the snapshot after generating the output of this issue,I am also curious to see if it matches with my code or not. Reopening the issue doesn't mean you should talk about anything or anyone's PR. @skeptrunedev look into this.

**Comment by anikdhabal** [comment]
Closed my PR. I think your PR is more intuitive.

**Comment by tobihans** [comment]
> > > I closed this before I really reviewed the other claim. It's a long ways off being correct honestly.
> > > In the future we will make a policy for this so it doesn't happen again.
> > 
> > 
> > I guess that was AI-generated.
> 
> Pls show me the snapshot after generating the output of this issue,I am also curious to see if it matches with my code or not. Reopening the issue doesn't mean you should talk about anything or anyone's PR. @skeptrunedev look into this.

Sorry about that.

**Comment by skeptrunedev** [comment]
Made a few final changes so the .env.dist's had the correct data, squashed, and added a proper commit message. 

It is all good now. Great work!

**Review by skeptrunedev — APPROVED** [review]

**Comment by skeptrunedev** [comment]
And star the repo if you have not yet! 

image

**Pull request merged**
