### PR TITLE
feature: toasts on important success and failure events

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes https://github.com/arguflow/vault-chat/issues/17

ps:- I've tested in the search page for better view.

success:-
Screenshot 2023-09-22 224811
Screenshot 2023-09-22 224524

error:-
Screenshot 2023-09-22 224653
Screenshot 2023-09-22 224607

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Example of how to trigger for future reference: 

```
createEffect(() => {
    const interval = setInterval(() => {
      const randomNumber = Math.floor(Math.random() * 101);
      const toastType = randomNumber % 2 == 0 ? "success" : "error";
      const newEvent = new CustomEvent("show-toast", {
        detail: {
          type: toastType,
          message: `This is my message ${randomNumber}`,
        },
      });
      window.dispatchEvent(newEvent);
    }, 1000);

    onCleanup(() => {
      clearInterval(interval);
    });
  });
  ````

**Review by skeptrunedev — APPROVED** [review]
This was great work. I made a few select changes to allow for multiple toasts, include the component in the tree, and round them. But that was all. Nice!

**Comment by anikdhabal** [comment]
> This was great work. I made a few select changes to allow for multiple toasts, include the component in the tree, and round them. But that was all. Nice!

Thank you🙏

**Pull request merged**
