### PR TITLE
feature: update docker-compose.yml with hardcoded container names

### PR DESCRIPTION
**Pull request by qnlbnsl**
## feature: update docker-compose.yml with hardcoded container names

PR related to a docker update to allow inter-container links.  @densumesh 

In the future we can remove the port definitions from the docker images for the database, qdrant, etc.... they can be accessed via the link functionality.

### CODE REVIEW

**Comment by skeptrunedev** [comment]
This is a great change. Tiny nit, could you change the commit message to `feature: update docker-compose.yml with hardcoded container names`.

**Comment by qnlbnsl** [comment]
> This is a great change. Tiny nit, could you change the commit message to `feature: update docker-compose.yml with hardcoded container names`.

i think you did.

**Comment by skeptrunedev** [comment]
> > This is a great change. Tiny nit, could you change the commit message to `feature: update docker-compose.yml with hardcoded container names`.
> 
> i think you did.

I changed the PR title but not the commit message. Although I can change it real quick, no worries.

**Comment by qnlbnsl** [comment]
okay done. I think that is what you were looking for?

**Review by skeptrunedev — APPROVED** [review]
really nice change! Thank you @qnlbnsl .

**Pull request merged**
