### PR TITLE
feature: change no-reply@arguflow.gg addresses in email_operator.rs to use a .env email

### LINKED ISSUE #445: feature: change no-reply@arguflow.gg addresses in `email_operator.rs` to use a .env email
### Description

While we allow users to set their own `SENDGRID_API_KEY` in the `.env`, we do not allow them to change which email is used. This is an issue as obviously every users sendgrid account will be connected to different domains.

We need to modify the email addresses in `email_operator.rs` to use emails from the `.env`. 

### Target(s)

`server`

### Requirement to close

All emails being sent through sendgrid use an address set via the `.env` . 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #445 
/claim #445

### CODE REVIEW

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
This env will also need to be added to `docker-compose.yml` . 

When you do that, please make sure to contain the change to the single commit. `git reset --soft @~1, git commit ... , git push --force

**Comment by anikdhabal** [comment]
> This env will also need to be added to `docker-compose.yml` .
> 
> When you do that, please make sure to contain the change to the single commit. `git reset --soft @~1, git commit ... , git push --force

Okk

**Comment by anikdhabal** [comment]
@skeptrunedev Done

**Comment by skeptrunedev** [comment]
I know it's annoying, but can you repush with the commit message as `feature: change no-reply@arguflow.gg addresses in email_operator.rs to use a .env email` :sweat_smile: 

At some point in the future, we are going to do semantic search on all the commits and it will be important to have them tagged properly with quality messages.

**Comment by anikdhabal** [comment]
> I know it's annoying, but can you repush with the commit message as `feature: change no-reply@arguflow.gg addresses in email_operator.rs to use a .env email` 😅
> 
> At some point in the future, we are going to do semantic search on all the commits and it will be important to have them tagged properly with quality messages.

OKK😅.

**Comment by anikdhabal** [comment]
@skeptrunedev Done

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
The root `.env.dist` also needs `SENDGRID_EMAIL_ADDRESS="no-reply@arguflow.com"` :sweat_smile: 

My bad on missing that before

**Comment by anikdhabal** [comment]
> The root `.env.dist` also needs `SENDGRID_EMAIL_ADDRESS="no-reply@arguflow.com"` 😅
> 
> My bad on missing that before

yeah, I feel it before that I'm missing something. Let me fix it  😅.

**Review by skeptrunedev — APPROVED** [review]
Great work!

**Pull request merged**
