### PR TITLE
cleanup: remove all code related to verifications

### PR DESCRIPTION
**Pull request by Hemxnt**
This marks my first-ever contribution to open source! While I'm still learning the ropes, I've taken the initiative to remove all code related to verifications. I appreciate the opportunity and welcome any feedback to improve.

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Hey! We really appreciate your contribution and would like to get this merged so you have your first ever contribution! 

There is a problem here in that you are deleting `migrations` files. You cannot delete database migrations because they represent a historical record of changes to your database schema and are essential for maintaining data consistency and integrity when rolling back or updating your database schema in the future. Deleting them can result in potential data inconsistencies and migration conflicts.

Can you `git reset --soft @~1` to soft revert your changes and then make a new commit where you do not remove any of the `.sql` files in the `migrations` folder? 

Once you do that, I think we may be able to get this merged.

**Review by skeptrunedev — COMMENTED** [review]
Will review this again once the sql files in the migrations folder are no longer removed. 

Also, make sure to star the repo! :heart: 

image

**Comment by Hemxnt** [comment]
Thanks for the quick response! 😊 I totally get why keeping those migration files is essential for data integrity.

No worries—I'll perform that soft reset and make sure those .sql files in the migrations folder stay put. Learning as I go, and your advice is super helpful!

Excited to get this sorted and contribute better, especially since it's helping with Hacktoberfest. 🚀

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
Sorry for the change request I know it feels a bit harsh, but just wanted to mark things clearly.

**Comment by Hemxnt** [comment]
No worries at all! Your feedback was really helpful. Thanks for taking the time to clarify things, it's all part of the learning process. 😊I'm happy to make the necessary changes and appreciate your guidance. If you have more suggestions or specific changes in mind, please feel free to let me know. I'm here to learn and contribute!

**Review by skeptrunedev — COMMENTED** [review]
This is looking good so far. I will complete a review shortly.

**Comment by skeptrunedev** [comment]
@Hemxnt so your PR was close, but there were still a few things missing and your code did not compile. I went back through it and got the Rust code to compile then adjusted the frontends to not use `verifications` either. I also removed the `verification` tables.

**Review by skeptrunedev — COMMENTED** [review]
Approved!

**Pull request merged**
