### PR TITLE
feat: env! macro added to throw error at compile time

### LINKED ISSUE #246: feature: use env! macro to throw error's at compile time.
This is for the `server` folder. Everywhere than an `env` var is loaded should throw an error at compile if it is not present once this issue is resolved.

However, the exception is env vars that are optional. Do not make them required please.

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #246 
/claim #246
env! macro added to throw error at compile time if env is not present.

### CODE REVIEW

**Comment by anikdhabal** [comment]
cc @skeptrunedev

**Comment by anikdhabal** [comment]
cc @skeptrunedev @fastfists

**Comment by skeptrunedev** [comment]
I cannot get this PR to compile @anikdhabal . 

Were you able to?

**Comment by skeptrunedev** [comment]
Maybe relevant - https://stackoverflow.com/questions/63041855/why-does-a-procedural-macro-not-see-environment-variables-set-by-dotenv-in-my-bu

**Comment by anikdhabal** [comment]
> I cannot get this PR to compile @anikdhabal .
> 
> Were you able to?

I am on it.

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
Currently cannot compile

**Comment by anikdhabal** [comment]
@skeptrunedev fixed and left unwraped_or as it is.

**Pull request closed without merging**
