### PR TITLE
feature: feeling lucky button

### LINKED ISSUE #465: feature: feeling lucky button
### Description

Allow the developer to pass in a csv of strings to a .env such that a user can hover over the "I'm feeling lucky" button and press it to make a random default search query. 

### Target(s)

`search`

### Requirement to close

- [ ] list of get lucky strings separated by commas are set in .env
- [ ] `SearchForm.tsx` picks up get lucky strings from .env
- [ ] add a button to `SearchForm.tsx` next to the `Create Evidence Card` button for `I'm feeling lucky`
- [ ] when user hovers over the "I'm feeling lucky button" text should scroll to the options present in the `.env` list and settle on 1 (reference google.com for this)
- [ ] "I'm feeling lucky button" has an animation if it expands horizontally so it looks smooth 
- [ ] when user presses "I'm feeling lucky button" it should cause a search to occur with the value that the scroll stopped on (reference google.com for this)

### PR commit requirements for a bounty claim

1 commit with the following message: 

"feature: feeling lucky button"

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #465
/claim #465

- [x] list of get lucky strings separated by commas are set in .env
- [x]  SearchForm.tsx picks up get lucky strings from .env
- [x]  add a button to SearchForm.tsx next to the Create Evidence Card button for I'm feeling lucky
- [x]  when user hovers over the "I'm feeling lucky button" text should scroll to the options present in the .env list and settle on 1 (reference google.com for this)
- [x]  "I'm feeling lucky button" has an animation if it expands horizontally so it looks smooth
- [x]  when user presses "I'm feeling lucky button" it should cause a search to occur with the value that the scroll stopped on (reference google.com for this)

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@skeptrunedev


https://github.com/arguflow/arguflow/assets/46300090/ae52a48b-052a-43e5-b66c-383f673b9457

**Comment by rishi-raj-jain** [comment]
Also, wrote some tailwind classes to make the button set responsive for mobile & desktop view.

# Mobile: Here are some screenshots of view OLD vs NEW

## OLD
Screenshot 2023-09-22 at 4 23 39 PM

## NEW
Screenshot 2023-09-22 at 4 24 01 PM

# Desktop: Here are some screenshots of view OLD vs NEW

## OLD
Screenshot 2023-09-22 at 4 23 28 PM

## NEW
Screenshot 2023-09-22 at 4 24 09 PM

**Review by skeptrunedev — APPROVED** [review]

**Comment by skeptrunedev** [comment]
@rishi-raj-jain my commits are not the most organized, but you should take a look at what I did. 

Your initial solution did not really do this the "solidJS" way and used a `.css` file instead of `tailwindcss`. I fixed all of that so this can be merged. :) 

Will still payout the bounty.

**Comment by rishi-raj-jain** [comment]
Thank you so much! 🙏

**Comment by rishi-raj-jain** [comment]
> Your initial solution did not really do this the "solidJS" way and used a .css file instead of tailwindcss. I fixed all of that so this can be merged. :)

Everything was solidjs except css, wasn't it?

**Comment by rishi-raj-jain** [comment]
But I get your point regarding tailwindcss! I'll make sure to use that in future PRs.

**Comment by skeptrunedev** [comment]
> > Your initial solution did not really do this the "solidJS" way and used a .css file instead of tailwindcss. I fixed all of that so this can be merged. :)
> 
> Everything was solidjs except css, wasn't it?

Nah, you wrote most of it in VanillaJS. Take a look at how I am triggering the effect w/ Solid. 

I get that you literally wrote it in a SolidJS component. I more mean that it you did not do it in the idiomatic "solid" way.

**Comment by rishi-raj-jain** [comment]
> Nah, you wrote most of it in VanillaJS. Take a look at how I am triggering the effect w/ Solid.

Ah okay, got that

**Comment by rishi-raj-jain** [comment]
@skeptrunedev

Would love to get the amount as promised for this one ✨

**Pull request merged**
